# Final Training Config

model: SegmentationUNet
loss: CustomWeightedLoss

path:
  train:
    source: F:/Stomach_X-ray/Pediatric_Abdominal_X-ray/Train/Source_Data
    label: F:/Stomach_X-ray/Pediatric_Abdominal_X-ray/Train/Labeling_Data 
  val:
    source: F:/Stomach_X-ray/Pediatric_Abdominal_X-ray/Validate/Source_Data
    label: F:/Stomach_X-ray/Pediatric_Abdominal_X-ray/Validate/Labeling_Data
  test:
    source: F:/Stomach_X-ray/Pediatric_Abdominal_X-ray/Test/Source_Data
    label: F:/Stomach_X-ray/Pediatric_Abdominal_X-ray/Test/Labeling_Data

parameters:
  seed: 42
  size: 512
  batch_size: 8
  epochs: 100
  learning_rate: 0.001
  num_classes: 5
  device: cuda
  optimizer: RMSprop
  scheduler_patience: 3
  patience: 10
  threshold: 0.01
