# Final Training Config

model: SegmentationUNet
loss: CustomWeightedLoss

data:
  train:
    source: F:/Stomach_X-ray/Pediatric_Abdominal_X-ray/Train/Source_Data
    label: F:/Stomach_X-ray/Pediatric_Abdominal_X-ray/Train/Labeling_Data 
  val:
    source: F:/Stomach_X-ray/Pediatric_Abdominal_X-ray/Validate/Source_Data
    label: F:/Stomach_X-ray/Pediatric_Abdominal_X-ray/Validate/Labeling_Data
  test:
    source: F:/Stomach_X-ray/Pediatric_Abdominal_X-ray/Test/Source_Data
    label: F:/Stomach_X-ray/Pediatric_Abdominal_X-ray/Test/Labeling_Data

parameters:
  seed: 42
  batch_size: 8
  epochs: 100
  learning_rate: 1e-4
  num_classes: 5
  device: cuda
  optimizer: RMSprop
  patience: 10
  threshold: 1e-3
